image: clojure:latest

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - clj -T:build compile
    - echo '{:username "'${CI_REGISTRY_USER}'" :password "'${CI_REGISTRY_PASSWORD}'"}' > .creds.edn
    - clj -Sdeps '{:mvn/local-repo "'${CI_PROJECT_DIR}'/.m2/repository"}' -T:container "$(< jib-gitlab.edn)"
  only:
    - tags